### ISSUE TITLE
this will never get version from the synse-server api

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-graphql#26]
the config option for version is defined and `2.0` is given as the default

```py
parser.add(
    '--version',
    choices=['2.0'],
    env_var='BACKEND_VERSION',
    default='2.0',
    help='The API version of the Synse instance being connected to.'
)
```

There is also a block to get the version from synse server
```py
    # if the version is unspecified, we'll have to get the version
    # from the synse instance.
    if version is None:
        r = SESSION.get(
            '{}/synse/version'.format(path),
            timeout=config.options.get('timeout'))
        if r.ok:
            version = r.json().get('api_version')
        else:
            logger.warning('Unable to get API version of Synse.')
            r.raise_for_status()
```

but the version it checks there is the version it gets from config. since a default exists, it will always use that if an override isn't set.

I'm thinking that `version` shouldn't be a configuration option at all and it should always get the version from synse server. Just my thought, and I'd like to hear other opinions

**Comment by Kontazler** [comment]
As of release [2.1.1](https://github.com/vapor-ware/synse-graphql/releases/tag/2.1.1) api version is maintained on a per-backend level, requested once, and stored. It is also refreshed if `404` is returned, indicating a responsive backend, but possible api mismatch.
